### ISSUE TITLE
Create a custom command to start development server setting up some options

### ISSUE THREAD

**Issue by Marlysson** [bocadilloproject/queso#3]
**Is your feature request related to a problem? Please describe.**

Currently when we start a project to see running in browser we put this in app.py file like:

```python
if __name__ == "__main__":
    app.run()
``` 

after run:

```bash
python app.py
```

**Describe the solution you'd like**
After implement this we will call it so:

```python
queso runserver -options

-options:
[-p] 8080
[-cors] (true | false)
....
```

**Describe alternatives you've considered**
/

**Implementation ideas**
Create a custom command on **queso** cli to encapsulate this routine and add some parameters to development server..

**Additional context**
/

**Comment by florimondmanca** [comment]
Thanks for putting this up!

FYI, uvicorn already has [a ton of useful built-in options](https://www.uvicorn.org/#command-line-options) for running an application, including choosing the host, port, number of workers, etc.

As I understand, the pain comes from having to type `if __name__ == "__main__": app.run()`. That's indeed plain boilerplate and as a user I'd also like to save myself writing those two same lines over and over.

So, perhaps this `runserver` command (although I think I'd like `start` better) could be a simple wrapper around the `uvicorn` command:

```bash
queso start [options]
# equivalent to:
uvicorn app:app [options]
```

We currently have two ways to start the dev server (`app.run()` + `python app.py`, and `uvicorn`), so having only One Officially Recommended Way would probably be better UX too.

I also just opened https://github.com/encode/uvicorn/issues/322 to see if file-based configuration for uvicorn could be implemented. If so, we could even have `queso start` read the options from a standardised config file, e.g. `serverconf.py`.

Also:

> ```python
> [-cors] (true | false)
> ```

CORS configuration is not something we can enable/disable when starting the dev server; it's a configuration item. I don't think this should be part of the `start` command.

However, we can imagine a separate scaffolding command, e.g. `queso init`, that would allow us to (interactively) select which options we want to enable on the app, e.g. turn on CORS, select the default port, etc. Perhaps that's a separate issue. :-)

Anyway, would you be willing to work on a minimal implementation for `queso start`? 😄

**Comment by Marlysson** [comment]
Which commands queso toolkit development should contains?

create project with predefined configs , start server... which other else ?

> Anyway, would you be willing to work on a minimal implementation for queso start? 😄

Sure :smile: I will open a PR.

**Comment by florimondmanca** [comment]
> Which commands queso toolkit development should contains?

I’m not sure yet. The idea is for Queso to gradually include more and more commands/features as needs arise, such as in this issue. :)

> Sure 😄 I will open a PR.

Cool! I don’t think there are contributing guidelines on this repo yet, but the setup is very much the same than for the Bocadillo main repo: https://github.com/bocadilloproject/bocadillo/blob/master/CONTRIBUTING.md

**Comment by florimondmanca** [comment]
@Marlysson Have you been working on this? If not, I'll gladly take this one! I thought it was time to give Queso some love. I've already refactored some internal bits and thought to push this out and release as 0.3. :-)

**Comment by Marlysson** [comment]
Hey @f

**Comment by Marlysson** [comment]
Hey @florimondmanca sorry for the late response... 
I was taking some effort on getting done this... But yet don't get done this.

You can get this.. It's better to me see how would be this approach.

**Comment by florimondmanca** [comment]
I'm closing this because Queso is retiring in favor of [Bocadillo CLI](../../bocadillo-cli), which has a project generation command that covers this use case. :-)
